version: "3"

services:
  postgres:
    container_name: user-managment-db
    image: postgres:16-alpine
    restart: always
    ports:
      - "${DB_HOST}:5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST_AUTH_METHOD: "trust"
      PGDATA: /data/postgres
    command: ["postgres", "-c", "log_statement=all"]
